### ISSUE TITLE
lut ! pb au lancement du serveur

### ISSUE THREAD

**Issue by schevall** [rmonnier/hypertube#1]
hey ! hey !
Bon deja, merci Robin, apparement sa a l'air deja bien avance l'auth, trop fort !

Chez moi j'arrive pas a lancer le serveur, j'ai cette erreur : 

/home/saims/Documents/Hypertube/api/node_modules/passport-oauth2/lib/strategy.js:82
  if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clientID option'); }
                           ^

TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (/home/saims/Documents/Hypertube/api/node_modules/passport-oauth2/lib/strategy.js:82:34)
    at new Strategy (/home/saims/Documents/Hypertube/api/node_modules/passport-google-oauth20/lib/strategy.js:52:18)
    at Object.<anonymous> (/home/saims/Documents/Hypertube/api/config/passport.js:63:14)
    at Module._compile (module.js:569:30)
    at loader (/home/saims/Documents/Hypertube/api/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/saims/Documents/Hypertube/api/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/saims/Documents/Hypertube/api/server.js:31:1)
    at Module._compile (module.js:569:30)
    at loader (/home/saims/Documents/Hypertube/api/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/saims/Documents/Hypertube/api/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at Object.<anonymous> (/home/saims/Documents/Hypertube/api/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
[nodemon] app crashed - waiting for file changes before starting...

Apparement il faudrait set une variable globale, l'ID. bref, j'ai commence a regarder le code et j'aurais des questions ! en tout cas ca a l'air patate =0.
je testerai mardi a l'ecole
bisoux

**Comment by rmonnier9** [comment]
Est-ce que tu as rajoute le fichier .env a la racine du dossier api ?

2017-09-10 18:09 GMT+02:00 schevall <notifications@github.com>:

**Comment by schevall** [comment]
Je dois créer un fichier vide avec touch ? et refaire un npm install après ? 
C'est marqué quelque part qu'il faut faire cette manip ? Je n'ai pas vu

**Comment by rmonnier9** [comment]
J'avais envoyé un fichier .env sur messenger à rajouter !
En pièce jointe aussi ici ;)

**Comment by schevall** [comment]
c'est pour ça ! j'avais pas vu le .env.. thx !

Le 11 septembre 2017 à 17:00, Robin Monnier <notifications@github.com> a
écrit :

**Comment by schevall** [comment]
le .env est placé, maintenant j'ai ça

(node:51192) DeprecationWarning: `openSet()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
✓ App is running at http://localhost:8080 in development mode
  Press CTRL-C to stop

Db.prototype.authenticate method will no longer be available in the next major release 3.x as MongoDB 3.6 will only allow auth against users in the admin db and will no longer allow multiple credentials on a socket. Please authenticate using MongoClient.connect with auth credentials.

Ça a l'air de venir de cette ligne la : mongoose.connect(process.env.MONGODB_URI);
Mais d'après la doc de moogoose, je ne vois pas se qui pourrait déconner
Et j'ai internal serveur error quand j'envoi des requete de l'app

**Comment by rmonnier9** [comment]
Le site marche quand même, c'est mongoose qui devra faire une MAJ

**Comment by schevall** [comment]
j'ai changé le proxy a 8080 dans le package.json de l'app. il etait a 8000. du coup les requetes passent maintenant
après j'ai ça : 

Error: CSRF token missing
    at checkCsrf (/Users/schevall/Documents/Hypertube/api/node_modules/lusca/lib/csrf.js:112:18)
    at /Users/schevall/Documents/Hypertube/api/server.js:77:5 
....
    at next (/Users/schevall/Documents/Hypertube/api/node_modules/express/lib/router/index.js:275:10)
POST /api/signin 403 39.635 ms - -


Error: CSRF token missing
    at checkCsrf (/Users/schevall/Documents/Hypertube/api/node_modules/lusca/lib/csrf.js:112:18)
    at /Users/schevall/Documents/Hypertube/api/server.js:77:5
...
    at next (/Users/schevall/Documents/Hypertube/api/node_modules/express/lib/router/index.js:275:10)
POST /api/signup/ 403 94.619 ms - -
